version: "3.4"

services:
    nginx:
        build:
            context: docker
            dockerfile: Nginx.Dockerfile
        ports:
            - ${APP_PORT}:80
        volumes:
            - ./:/var/www/html
    fpm:
        build:
            context: docker
            dockerfile: Fpm.Dockerfile
        volumes:
            - ./:/var/www/html
    mysql:
        image: mysql:5.7.35
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
